### ISSUE TITLE
Add a Favicon icon

### ISSUE THREAD

**Issue by harshchandwani** [harshchandwani/tindog#2]
This is an example of Favicons

You have to download Tinder Icon from the internet and add it to the HTML file. Please ensure it is of good size.

![nlfmvb9rg7y6gkehb456](https://user-images.githubusercontent.com/67815775/132991361-101cd5d7-5fd4-4c3c-9f55-c8ea5b01e807.png)

**Comment by jatin-02** [comment]
I know how to do it. You can assign it to me.

**Comment by harshchandwani** [comment]
Hi Jatin Soni,

There is an issue already raised in the repository, you can continue
working on it. And please Star the repository.
If you have any questions related, please let me know.

Have a nice day,
Harsh Chandwani

**Comment by harshchandwani** [comment]
Issue Resolved by @jatin-02
